### PR TITLE
fixed payment type date error

### LINKED ISSUE #19: Bug: Payment type info is incorrect
Customers are complaining that the expiration date on their payment types are incorrect.

### PR DESCRIPTION
**Pull request by andrew-webb07**
Description of PR that completes issue here...

## Changes

- bangazonapi/views/paymenttype.py
- the create method had it's expiration_date and create_date property values backwards
        new_payment.expiration_date = request.data["create_date"]
        new_payment.create_date = request.data["expiration_date"]

- changed to:
        new_payment.expiration_date = request.data["expiration_date"]
        new_payment.create_date = request.data["create_date"]

## Testing

Description of how to test code...

- [ ] git fetch all
- [ ] git ticket-19-payment-error
- [ ] run python3 manage.py test tests -v 1 in your vs code terminal
- [ ] The tests results should show "OK" after the tests are run

## Related Issues

- Fixes #19

### CODE REVIEW

**Review by heymonicakay — CHANGES_REQUESTED** [review]
Your PR description is missing, and the steps to test are unclear.. How do I see the database? What test suite am I supposed to be running? What changes am I looking for? How can I test the changes you made? What is the expected outcome of those tests?

Please revise and resubmit!

**Comment by andrew-webb07** [comment]
> Your PR description is missing, and the steps to test are unclear.. How do I see the database? What test suite am I supposed to be running? What changes am I looking for? How can I test the changes you made? What is the expected outcome of those tests?
> 
> Please revise and resubmit!

**Review by heymonicakay — COMMENTED** [review]
Thanks for adding those instructions! HUGE improvement!!

**Review by heymonicakay — APPROVED** [review]

**Comment by heymonicakay** [comment]
Great work, and awesome job utilizing the test suite here. Thanks Andrew!

**Pull request merged**
